### ISSUE TITLE
What is this ?

### ISSUE THREAD

**Issue by ocZio** [ARMmbed/mbed-client-examples#21]
```cpp
uint16_t port = rand() % 65535 + 12345;
```
source: https://github.com/ARMmbed/mbed-client-examples/blob/master/source/main.cpp#L85

**Comment by yogpan01** [comment]
This is a listening port for incoming data but there is currently issue in DTLS handling on mbed Device Server side that it caches the port and will not allow re-connection requests on same port. So, we need to add randomization so that reseting and re-connecting this example will work.
Once issue is resolved on mbed Device Server end , we will no longer require to do this randomization of port value.

**Comment by ocZio** [comment]
Thanks for the explanation yogplan01.

So what would happen if the port get's a larger value than 65535 ?

**Comment by yogpan01** [comment]
It won't go above 65535 as the data type is uint16_t , it will wrap around :)

**Comment by ocZio** [comment]
Thank you!
